### PR TITLE
Lazy-compute-ESS

### PR DESCRIPTION
**Pull request by ParadaCarleton**

### CODE REVIEW

**Comment by ParadaCarleton** [comment]
@sethaxen This PR adds a keyword arg for ESS calculations. If set to `false`, `psis` replaces the ESS values with a singleton matrix containing one `NaN`. It should avoid duplicate ESS computations and it makes the code a bit cleaner; do you think it's good?

**Comment by sethaxen** [comment]
What I don't like about this approach is that it's still allocating a vector that the user doesn't necessarily want. I still prefer a lazy computation of the vector only if the user requests it, which can happen one of two ways:
1. The approach in #51, using `getproperty`
2. OR overload `psis_ess(::Psis)` and `psis_sup_ess(::Psis)` and export `psis_ess` and `psis_sup_ess`

I chose (1) earlier so that the same API is supported, but I slightly prefer something like (2).

**Comment by ParadaCarleton** [comment]
> What I don't like about this approach is that it's still allocating a vector that the user doesn't necessarily want. I still prefer a lazy computation of the vector only if the user requests it, which can happen one of two ways:
> 
> 1. The approach in [Avoid computing ess and sup_ess in `psis` #51](https://github.com/TuringLang/ParetoSmooth.jl/pull/51), using `getproperty`
> 2. OR overload `psis_ess(::Psis)` and `psis_sup_ess(::Psis)` and export `psis_ess` and `psis_sup_ess`
> 
> I chose (1) earlier so that the same API is supported, but I slightly prefer something like (2).

Do you think the extra allocation is a meaningful problem? When `ess=false` is passed the function allocates a singleton, so it takes ~no time or memory.

That being said, I just realized that memoizing `psis_ess` should accomplish the same goal, so I suppose I can do that instead if you want.

**Comment by sethaxen** [comment]
> Do you think the extra allocation is a meaningful problem? When `ess=false` is passed the function allocates a singleton, so it takes ~no time or memory.

It's not about the extra allocation, it's about complexity of the code and interface. Your proposal introduces an additional keyword argument and allocates a vector that is essentially empty, and this seems unnecessary, when you can use either of the two options I suggested. The first would do neither of these things, while the second would export one additional function; in neither case is the vector allocated unless the user requests it.

> That being said, I just realized that memoizing `psis_ess` should accomplish the same goal, so I suppose I can do that instead if you want.

There's no need to memoize. A user is unlikely to call `psis_ess` on the same `Psis` object twice, and this just adds code complexity and a new dependency.

What do you dislike about either of the options I suggested?

**Comment by ParadaCarleton** [comment]
> > Do you think the extra allocation is a meaningful problem? When `ess=false` is passed the function allocates a singleton, so it takes ~no time or memory.
> 
> It's not about the extra allocation, it's about complexity of the code and interface. Your proposal introduces an additional keyword argument and allocates a vector that is essentially empty, and this seems unnecessary, when you can use either of the two options I suggested. The first would do neither of these things, while the second would export one additional function; in neither case is the vector allocated unless the user requests it.
> 
> > That being said, I just realized that memoizing `psis_ess` should accomplish the same goal, so I suppose I can do that instead if you want.
> 
> There's no need to memoize. A user is unlikely to call `psis_ess` on the same `Psis` object twice, and this just adds code complexity and a new dependency.
> 
> What do you dislike about either of the options I suggested?

I'd be very surprised if no users at all want to see the ESS twice, given the ESS displays whenever a Psis object is called in the REPL. I suppose I have three concerns: 
1. Wasted computation if the ESS is recalculated every time the user wants to take a look at the ESS values.
2. Calculating the ESS lazily makes performance behavior very unintuitive. It's weird for running a function to be fast, but then have it be very slow to access a property of a struct, which is usually close to instant. It's especially weird for it to be very slow to read a display table in the REPL when computation is finished.
3. I feel as though the implementation here is less complex rather than more, since the code is a bit shorter. An extra keyword argument adds almost no complexity relative to having to overload several methods.

If you have concerns about returning an empty array for `psis_ess`, we can make it so that trying to access these fields when they don't exist throws an error. I think 1 and 2 are obviously not a big deal for people who don't want to access the ESS, but most people should be reading those -- we want them to be checking diagnostics.

**Pull request merged**
