### PR TITLE
Setup CI and Documenter

### PR DESCRIPTION
**Pull request by mohamed82008**
This PR sets up CI and documenter for this package. CI wasn't working because of the master/main branch name confusion.

### CODE REVIEW

**Comment by mohamed82008** [comment]
@ParadaCarleton I think the tests are failing. But that's not related to this PR.

**Comment by ParadaCarleton** [comment]
@mohamed82008 Thanks, that's very weird. They're all doing just fine locally. Perhaps there's something weird with floats? I know `@fastmath` can give different results on different hardware...

**Comment by ParadaCarleton** [comment]
Ahh, hmm, it seems like it can't sample multiple chains in parallel? Maybe that's why. Does the behavior of chains change when they're sampled in parallel? Maybe the RNG is different -- the tests set a seed, but maybe chains sampled in parallel use their own RNGs, while chains sampled in series all use a different RNG.

**Comment by mohamed82008** [comment]
I will need to look into it.

**Comment by ParadaCarleton** [comment]
Hmm; I'll merge for now then.

**Pull request merged**
